var init_data = {
    'app': {
        "version": 13,
        "collapse_shown": null,
        "collapse_shown_animal": null,
        "settings": {
            "show_categories": true,
            "show_alpha": false,
            "show_critters": true,
            "show_legend": true
        },
        "view": "default",
        "help_shown": false
    },
    'categories': {
        1: {"name": "Farmland", "stamped": 0, "sampled": 0, "total": 11},
        2: {"name": "Desert", "stamped": 0, "sampled": 0, "total": 14},
        3: {"name": "Wetland", "stamped": 0, "sampled": 0, "total": 13},
        4: {"name": "Mnt. & Grass", "stamped": 0, "sampled": 0, "total": 14},
        5: {"name": "Forest & River", "stamped": 0, "sampled": 0, "total": 13},
        6: {"name": "Common Critters", "stamped": 0, "sampled": 0, "total": 11},
        7: {"name": "Dark", "stamped": 0, "sampled": 0, "total": 11},
        8: {"name": "Light", "stamped": 0, "sampled": 0, "total": 10},
        9: {"name": "Red & Blonde", "stamped": 0, "sampled": 0, "total": 12},
        10: {"name": "Patterned", "stamped": 0, "sampled": 0, "total": 9}
    },
    'animals': {
        1: {"name":     "Florida Cracker Cow",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        2: {"name":     "Angus Bull",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        3: {"name":     "Devon Bull",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        4: {"name":     "Hereford Bull",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        5: {"name":     "Angus Ox",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        6: {"name":     "Devon Ox",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        7: {"name":     "Old Spot Pig",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        8: {"name":     "Berkshire Pig",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        9: {"name":     "Big China Pig",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        10: {"name":     "Merino Sheep",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        11: {"name":     "Alpine Goat",
            "category": 1,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        12: {"name":     "Desert Iguana",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        13: {"name":     "Banded Gila Monster",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        14: {"name":     "Nine-Banded Armadillo",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        15: {"name":     "Baja Calif. Prongh. Buck",
            "category": 2,
            "stamped":  false,
            "samples":  0,
            "type": "normal"},
        16: {"name":     "Baja Calif. Prongh. Doe",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        17: {"name":     "Collared Peccary",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        18: {"name":     "Sonoran Pronghorn Buck",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        19: {"name":     "Sonoran Pronghorn Doe",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        20: {"name":     "Desert Bighorn Ram",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        21: {"name":     "Desert Bighorn Sheep",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        22: {"name":     "Sierra Nevada Bighorn Ram",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        23: {"name":     "Sierra Nevada Bighorn Sheep",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        24: {"name":     "Black-Tailed Rattlesnake",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        25: {"name":     "Cougar",
            "category": 2,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        26: {"name":     "American Alligator (small)",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        27: {"name":     "Green Iguana",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        28: {"name":     "Alligator Snapping Turtle",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        29: {"name":     "Panther",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        30: {"name":     "Florida Panther",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        31: {"name":     "American Alligator",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        32: {"name":     "Diamondback Rattlesnake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        33: {"name":     "Midland Water Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        34: {"name":     "Timber Rattlesnake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        35: {"name":     "Northern Copperhead Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        36: {"name":     "Southern Copperhead Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        37: {"name":     "Cottonmouth Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        38: {"name":     "Northern Water Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        39: {"name":     "Rocky Mountain Bull Elk",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        40: {"name":     "Rocky Mountain Cow Elk",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        41: {"name":     "American Badger",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        42: {"name":     "Gray Wolf",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        43: {"name":     "Timber Wolf",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        44: {"name":     "Rocky Mnt. Bighorn Ram",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        45: {"name":     "Rocky Mnt. Bighorn Sheep",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        46: {"name":     "California Valley Coyote",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        47: {"name":     "Whitetail Buck",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        48: {"name":     "Whitetail Deer",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        49: {"name":     "Wild Boar",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        50: {"name":     "American Bison",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        51: {"name":     "American Pronghorn Buck",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        52: {"name":     "American Pronghorn Doe",
            "category": 4,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        53: {"name":     "American Black Bear",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        54: {"name":     "North American Beaver",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        55: {"name":     "North American Raccoon",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        56: {"name":     "American Red Fox",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        57: {"name":     "American Gray Fox",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        58: {"name":     "Silver Fox",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        59: {"name":     "Striped Skunk",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        60: {"name":     "Virginia Opossum",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        61: {"name":     "American Muskrat",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        62: {"name":     "Western Bull Moose",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        63: {"name":     "Western Moose",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        64: {"name":     "Grizzly Bear",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        65: {"name":     "Black-Tailed Jackrabbit",
            "category": 5,
            "stamped":  false,
            "samples":  0, 
            "type": "normal"},
        66: {"name":     "Little Brown Bat",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        67: {"name":     "American Bullfrog",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        68: {"name":     "Western Chipmunk",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        69: {"name":     "Cuban Land Crab",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        70: {"name":     "Black Rat",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        71: {"name":     "Brown Rat",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        72: {"name":     "American Red Squirrel",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        73: {"name":     "Western Gray Squirrel",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        74: {"name":     "Black Squirrel",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        75: {"name":     "Western Toad",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},
        76: {"name":     "Sonoran Desert Toad",
            "category": 6,
            "stamped":  false,
            "samples":  0,
            "type": "critter"},

        77: {"name":     "Teca gator",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        78: {"name":     "Night Beaver",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        79: {"name":     "Tatanka Bison",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        80: {"name":     "Shadow Buck",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        81: {"name":     "Sapa Cougar",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        82: {"name":     "Midnight Coyote",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        83: {"name":     "Katata Elk",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        84: {"name":     "Onyx Wolf",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        85: {"name":     "Nightwalker Panther",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        86: {"name":     "Rutile Ram",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        87: {"name":     "Knight Moose",
            "category": 7,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},

        88: {"name":     "Moon Beaver",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        89: {"name":     "Winyan Bison",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        90: {"name":     "Snow Buck",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        91: {"name":     "Iguga Cougar",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        92: {"name":     "Milk Coyote",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        93: {"name":     "Imahne Elk",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        94: {"name":     "Moonstone Wolf",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        95: {"name":     "Ghost Panther",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        96: {"name":     "Gabbro Ram",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        97: {"name":     "Snowflake Moose",
            "category": 8,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},

        98: {"name":     "Sun Gator",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        99: {"name":     "Banded Gator",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        100: {"name":     "Payta Bison",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        101: {"name":     "Wapaka Boar",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        102: {"name":     "Red Streak Coyote",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        103: {"name":     "Ozula Elk",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        104: {"name":     "Emerald Wolf",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        105: {"name":     "Ridgeback Spirit Bear",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        106: {"name":     "Golden Spirit Bear",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        107: {"name":     "Zizi Beaver",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        108: {"name":     "Cogi Boar",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        109: {"name":     "Ruddy Moose",
            "category": 9,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
            
        110: {"name":     "Owiza Bear",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        111: {"name":     "Ichahi Boar",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        112: {"name":     "Mud Runner Buck",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        113: {"name":     "Maza Cougar",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        114: {"name":     "Ota Fox",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        115: {"name":     "Marble Fox",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        116: {"name":     "Cross Fox",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        117: {"name":     "Iwakta Panther",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
        118: {"name":     "Chalkhorn Ram",
            "category": 10,
            "stamped":  false,
            "samples":  0,
            "type": "legendary"},
    }
};

var animal_properties = ['tracked','killed','skinned','studied','sedated','sampled','photographed'];

function migrateData() {
    var migrated = false;
    if (data.app.version == 1) {
        migrated = true;
        data.animals[10].name = "Merino sheep";
    }
    if (data.app.version == 2) {
        migrated = true;
        data.animals[15].name = "Baja Calif. Prongh. Buck";
        data.animals[16].name = "Baja Calif. Prongh. Doe";
        data.categories[4].name = "Mnt. & Grass";
    }
    if (data.app.version == 3) {
        migrated = true;
        data.animals[44].name = "Rocky Mnt. Bighorn Ram";
        data.animals[45].name = "Rocky Mnt. Bighorn Sheep";
    }
    if (data.app.version == 4) {
        migrated = true;
        data.animals[42].name = "Grey Wolf";
    }
    if (data.app.version == 5) {
        migrated = true;
        data.app.view = "default";
    }
    if (data.app.version == 6) {
        migrated = true;
        data.animals[42].name = "Gray Wolf";
        data.animals[57].name = "American Gray Fox";
    }
    if (data.app.version == 7) {
        migrated = true;
        for (i in data.animals) {
            if (data.animals[i].samples > 1 || data.animals.stamped === true) {
                data.animals[i].studied = true;
            }
        }
    }
    if (data.app.version == 8) {
        migrated = true;
        
        data.categories[6] = init_data.categories[6];

        for (i = 66; i < 77; i++) {
            data.animals[i] = init_data.animals[i];
        }
    }
    if (data.app.version == 9) {
        migrated = true;
        data.app.settings = init_data.app.settings;
    }
    if (data.app.version == 10) {
        migrated = true;

        for (i in data.animals) {
            if (data.animals[i].can_sample === false) {
                delete data.animals[i].can_sample;
                data.animals[i].type = "critter";
            } else {
                data.animals[i].type = "normal";
            }
        }
    }
    if (data.app.version == 11) {
        migrated = true;
        
        data.categories[7] = init_data.categories[7];
        data.categories[8] = init_data.categories[8];
        data.categories[9] = init_data.categories[9];
        data.categories[10] = init_data.categories[10];

        for (i = 77; i < 119; i++) {
            data.animals[i] = init_data.animals[i];
        }
        data.app.settings.show_legend = true;
    }
    if (data.app.version == 12) {
        migrated = true;
        
        data.categories[7].name = "Dark";
        data.categories[8].name = "Light";
        data.categories[9].name = "Red & Blonde";
        data.categories[10].name = "Patterned";
    }   

    if (migrated) {
        data.app.version++;
        showNote("Upgraded to data version: "+data.app.version);
        commit();
        migrateData();
    }
}