var init_data = {
    'app': {
        "version": 8,
        "collapse_shown": null,
        "collapse_shown_animal": null,
        "view": "default"
    },
    'categories': {
        1: {"name": "Farmland", "stamped": 0, "sampled": 0, "total": 11},
        2: {"name": "Desert", "stamped": 0, "sampled": 0, "total": 14},
        3: {"name": "Wetland", "stamped": 0, "sampled": 0, "total": 13},
        4: {"name": "Mnt. & Grass", "stamped": 0, "sampled": 0, "total": 14},
        5: {"name": "Forest & River", "stamped": 0, "sampled": 0, "total": 13}
    },
    'animals': {
        1: {"name":     "Florida Cracker Cow",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        2: {"name":     "Angus Bull",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        3: {"name":     "Devon Bull",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        4: {"name":     "Hereford Bull",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        5: {"name":     "Angus Ox",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        6: {"name":     "Devon Ox",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        7: {"name":     "Old Spot Pig",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        8: {"name":     "Berkshire Pig",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        9: {"name":     "Big China Pig",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        10: {"name":     "Merino Sheep",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        11: {"name":     "Alpine Goat",
            "category": 1,
            "stamped":  false,
            "samples":  0},
        12: {"name":     "Desert Iguana",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        13: {"name":     "Banded Gila Monster",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        14: {"name":     "Nine-Banded Armadillo",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        15: {"name":     "Baja Calif. Prongh. Buck",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        16: {"name":     "Baja Calif. Prongh. Doe",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        17: {"name":     "Collared Peccary",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        18: {"name":     "Sonoran Pronghorn Buck",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        19: {"name":     "Sonoran Pronghorn Doe",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        20: {"name":     "Desert Bighorn Ram",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        21: {"name":     "Desert Bighorn Sheep",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        22: {"name":     "Sierra Nevada Bighorn Ram",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        23: {"name":     "Sierra Nevada Bighorn Sheep",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        24: {"name":     "Black-Tailed Rattlesnake",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        25: {"name":     "Cougar",
            "category": 2,
            "stamped":  false,
            "samples":  0},
        26: {"name":     "American Alligator (small)",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        27: {"name":     "Green Iguana",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        28: {"name":     "Alligator Snapping Turtle",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        29: {"name":     "Panther",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        30: {"name":     "Florida Panther",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        31: {"name":     "American Alligator",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        32: {"name":     "Diamondback Rattlesnake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        33: {"name":     "Midland Water Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        34: {"name":     "Timber Rattlesnake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        35: {"name":     "Northern Copperhead Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        36: {"name":     "Southern Copperhead Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        37: {"name":     "Cottonmouth Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        38: {"name":     "Northern Water Snake",
            "category": 3,
            "stamped":  false,
            "samples":  0},
        39: {"name":     "Rocky Mountain Bull Elk",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        40: {"name":     "Rocky Mountain Cow Elk",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        41: {"name":     "American Badger",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        42: {"name":     "Gray Wolf",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        43: {"name":     "Timber Wolf",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        44: {"name":     "Rocky Mnt. Bighorn Ram",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        45: {"name":     "Rocky Mnt. Bighorn Sheep",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        46: {"name":     "California Valley Coyote",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        47: {"name":     "Whitetail Buck",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        48: {"name":     "Whitetail Deer",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        49: {"name":     "Wild Boar",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        50: {"name":     "American Bison",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        51: {"name":     "American Pronghorn Buck",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        52: {"name":     "American Pronghorn Doe",
            "category": 4,
            "stamped":  false,
            "samples":  0},
        53: {"name":     "American Black Bear",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        54: {"name":     "North American Beaver",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        55: {"name":     "North American Raccoon",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        56: {"name":     "American Red Fox",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        57: {"name":     "American Gray Fox",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        58: {"name":     "Silver Fox",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        59: {"name":     "Striped Skunk",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        60: {"name":     "Virginia Opossum",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        61: {"name":     "American Muskrat",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        62: {"name":     "Western Bull Moose",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        63: {"name":     "Western Moose",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        64: {"name":     "Grizzly Bear",
            "category": 5,
            "stamped":  false,
            "samples":  0},
        65: {"name":     "Black-Tailed Jackrabbit",
            "category": 5,
            "stamped":  false,
            "samples":  0},
    }
};

var animal_properties = ['tracked','killed','skinned','studied','sedated','sampled','photographed'];

function migrateData() {
    var migrated = false;
    if (data.app.version == 1) {
        migrated = true;
        data.animals[10].name = "Merino sheep";
    }
    if (data.app.version == 2) {
        migrated = true;
        data.animals[15].name = "Baja Calif. Prongh. Buck";
        data.animals[16].name = "Baja Calif. Prongh. Doe";
        data.categories[4].name = "Mnt. & Grass";
    }
    if (data.app.version == 3) {
        migrated = true;
        data.animals[44].name = "Rocky Mnt. Bighorn Ram";
        data.animals[45].name = "Rocky Mnt. Bighorn Sheep";
    }
    if (data.app.version == 4) {
        migrated = true;
        data.animals[42].name = "Grey Wolf";
    }
    if (data.app.version == 5) {
        migrated = true;
        data.app.view = "default";
    }
    if (data.app.version == 6) {
        migrated = true;
        data.animals[42].name = "Gray Wolf";
        data.animals[57].name = "American Gray Fox";
    }
    if (data.app.version == 7) {
        migrated = true;
        for (i in data.animals) {
            if (data.animals[i].samples > 1 || data.animals.stamped === true) {
                data.animals[i].studied = true;
            }
        }
    }

    if (migrated) {
        data.app.version++;
        console.log("Upgrade to data version: "+data.app.version);
        commit();
        migrateData();
    }
}